name: baking_notes
description: A Flutter app for baking notes
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  path: ^1.8.3
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^19.0.0
  vibration: ^3.1.3
  audioplayers: ^6.4.0
  flutter_svg: ^2.0.5
  lottie: ^3.3.1
  provider: ^6.0.5
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"  # Color de fondo (opcional)